"use client";

import { useEffect, useState } from "react";
import { Bell, CheckCheck } from "lucide-react";
import { AuthGuard } from "@/components/auth-guard";
import { domainApi } from "@/lib/domain-api";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

function NotificationsContent() {
  const [notifications, setNotifications] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  async function load() {
    setLoading(true);

    try {
      setNotifications(await domainApi.notifications.list());
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    load();
  }, []);

  async function markRead(id: number) {
    await domainApi.notifications.markRead(id);
    await load();
  }

  async function markAll() {
    await domainApi.notifications.markAllRead();
    await load();
  }

  return (
    <main className="min-h-screen bg-slate-50">
      <div className="mx-auto max-w-4xl px-6 py-10">
        <div className="mb-8 flex items-end justify-between">
          <div>
            <div className="flex items-center gap-3">
              <Bell className="h-6 w-6" />
              <h1 className="text-3xl font-semibold">
                Notifications
              </h1>
            </div>

            <p className="mt-2 text-sm text-slate-500">
              Internal workflow notifications generated by domain events.
            </p>
          </div>

          <Button variant="outline" onClick={markAll}>
            <CheckCheck className="mr-2 h-4 w-4" />
            Mark all read
          </Button>
        </div>

        <Card>
          <CardContent className="p-0">
            {loading ? (
              <div className="p-8 text-sm text-slate-500">
                Loading notifications…
              </div>
            ) : notifications.length === 0 ? (
              <div className="p-10 text-center">
                <p className="font-medium">You are all caught up</p>
                <p className="mt-1 text-sm text-slate-500">
                  No internal notifications are waiting.
                </p>
              </div>
            ) : (
              <div className="divide-y divide-slate-200">
                {notifications.map((notification) => (
                  <div
                    key={notification.id}
                    className={`p-5 ${
                      notification.is_read ? "bg-white" : "bg-slate-50"
                    }`}
                  >
                    <div className="flex items-start justify-between gap-5">
                      <div>
                        <p className="font-medium">
                          {notification.title}
                        </p>
                        <p className="mt-1 text-sm text-slate-600">
                          {notification.message}
                        </p>
                        <p className="mt-2 text-xs text-slate-400">
                          {notification.created_at}
                        </p>
                      </div>

                      {!notification.is_read && (
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => markRead(notification.id)}
                        >
                          Mark read
                        </Button>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </main>
  );
}

export default function NotificationsPage() {
  return (
    <AuthGuard>
      <NotificationsContent />
    </AuthGuard>
  );
}
